### ISSUE TITLE
[BUG] NullPointerException when Building Creative Mode Tab Contents in Complicated Bees Mod

### ISSUE THREAD

**Issue by TheButterbrotMan** [ACCBDD/complicated_bees#21]
**Version of the mod**
Complicated Bees 1.20.1-1.1.0

**Describe the bug**
When attempting to join the server, a NullPointerException occurs during the process of building creative mode tab contents. This prevents players from successfully joining the server.

**To Reproduce**
1. Start the Minecraft server with the Complicated Bees mod installed
2. Attempt to join the server as a player
3. Server fails to place the player in the world due to the error

**Expected behavior**
The server should successfully build the creative mode tab contents and allow the player to join the world without errors.

**Error Logs**
```
[03:49:22] [Server thread/ERROR]: Couldn't place player in world
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at com.accbdd.complicated_bees.ComplicatedBees.lambda$static$1(ComplicatedBees.java:127) ~[complicated_bees-1.20.1-1.1.0.jar%23270!/:1.1.0]
	at net.minecraftforge.common.ForgeHooks.onCreativeModeTabBuildContents(ForgeHooks.java:1627) ~[forge-1.20.1-47.3.0-universal.jar%23349!/:?]
	at net.minecraft.world.item.CreativeModeTab.m_269498_(CreativeModeTab.java:129) ~[client-1.20.1-20230612.114412-srg.jar%23344!/:?]
	at net.minecraft.world.item.CreativeModeTabs.m_268957_(CreativeModeTabs.java:1696) ~[client-1.20.1-20230612.114412-srg.jar%23344!/:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at net.minecraft.world.item.CreativeModeTabs.m_269421_(CreativeModeTabs.java:1695) ~[client-1.20.1-20230612.114412-srg.jar%23344!/:?]
	at net.minecraft.world.item.CreativeModeTabs.m_269226_(CreativeModeTabs.java:1710) ~[client-1.20.1-20230612.114412-srg.jar%23344!/:?]
	at net.mehvahdjukaar.sawmill.RecipeSorter.refreshIfNeeded(RecipeSorter.java:48) ~[sawmill-1.20-1.4.3.jar%23325!/:?]
	at net.mehvahdjukaar.sawmill.RecipeSorter.sendOrderToClient(RecipeSorter.java:84) ~[sawmill-1.20-1.4.3.jar%23325!/:?]
	at net.mehvahdjukaar.sawmill.forge.SawmillModImpl.dataSync(SawmillModImpl.java:38) ~[sawmill-1.20-1.4.3.jar%23325!/:?]
	at net.mehvahdjukaar.sawmill.forge.__SawmillModImpl_dataSync_OnDatapackSyncEvent.invoke(.dynamic) ~[sawmill-1.20-1.4.3.jar%23325!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:188) ~[client-1.20.1-20230612.114412-srg.jar%23344!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:139) ~[client-1.20.1-20230612.114412-srg.jar%23344!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:126) ~[client-1.20.1-20230612.114412-srg.jar%23344!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.redirect$zoh000$handlePlayerJoin(ServerLoginPacketListenerImpl.java:563) ~[client-1.20.1-20230612.114412-srg.jar%23344!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:70) ~[client-1.20.1-20230612.114412-srg.jar%23344!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[client-1.20.1-20230612.114412-srg.jar%23344!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.20.1-20230612.114412-srg.jar%23344!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[client-1.20.1-20230612.114412-srg.jar%23344!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23344!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23344!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23344!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23344!/:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

This error log shows a NullPointerException occurring in the Complicated Bees mod when trying to build the contents of a creative mode tab, preventing the player from joining the server.

**Comment by ACCBDD** [comment]
solved! thank you for reporting this :)

**Comment by TheButterbrotMan** [comment]
> solved! thank you for reporting this :)

Unfortunately, the issue with the `Complicated Bees` mod has not been fully resolved and continues to occur. The latest log indicates that the `NullPointerException` is still present when trying to build the creative mode tab contents, preventing players from joining the server. You can view the details in the latest log here: [Latest Log](https://gist.github.com/TheButterbrotMan/3de000a8ff86d7326c6bc6cd740ca755).

**Comment by ACCBDD** [comment]
hmm - in my testing I can't reproduce this. what's your modlist?

**Comment by TheButterbrotMan** [comment]
With the new update, it's working now! The issue has been resolved.
